### PR TITLE
Invalid main field in package.json

### PR DESCRIPTION
**Pull request by Vikasg7**
Fixed package.json for following warning.  
```
(node:6644) [DEP0128] DeprecationWarning: Invalid 'main' field in 'E:\Desktop\Nodejs\XXXX-XXXX\node_modules\multi-hashing\package.json' of 'multihashing'. 
Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
```

### CODE REVIEW

**Comment by Vikasg7** [comment]
@zone117x Could you please merge this when you have time? It will take away that `warning` from all the project which use this repo as a dependency.  
Thanks!

**Comment by Vikasg7** [comment]
Fixed `Error: Module did not self-register. ERR_DLOPEN_FAILED` when `require`ing the module twice in the project.  
More explanation on this error [here](https://github.com/schroffl/node-lzo/issues/10).  
Fix was suggested [here](https://github.com/nodejs/node/issues/21783#issuecomment-429637117)

**Comment by zone117x** [comment]
Looks like this is failing to build or pass tests

**Comment by zone117x** [comment]
Looks like the `scryptjane` test vectors are failing. Is this related to the algo having some time component where it no longer works with a current date? Perhaps the that test should be disabled.

**Comment by Vikasg7** [comment]
Not sure about scrypt jane, ScriptJane tests were already failing before I made my changes.

**Comment by zone117x** [comment]
> Not sure about scrypt jane, ScriptJane tests were already failing before I made my changes.

Can you just disable the scrypt jane tests in your PR and then we can ensure everything else passes and we can merge.

**Review by zone117x — APPROVED** [review]
Thanks @Vikasg7!

**Comment by Vikasg7** [comment]
Thanks for merging this.

**Pull request merged**
