### PR TITLE
Add new nodejs support

### PR DESCRIPTION
**Pull request by bitbandi**
First i rewrite the code a little, this reduce the size. And add the new nodejs support (tested with 4.8.7, 6.13.1 and 9.8.0 nodejs versions), and add travis test for all nodejs versions

### CODE REVIEW

**Comment by Punkoivan** [comment]
Hello @bitbandi, first of all thanks for your work!
I've found your pull request and decided to try use your multi-hashing module.
I can't open issue in your repo, so want to ask here.

All compiled just fine, but when I do node init.js, next error appears:
```
2018-03-20 21:35:53 [Master]    [PoolSpawner] Fork 5 died, spawning replacement worker...
2018-03-20 21:35:53 [Switching] [Setup] (Thread 8) Loading last proxy state from redis
2018-03-20 21:35:53 [Pool]      [coin] (Thread 8) Share processing setup with redis (redis:6379)

buffer.js:164
      throw new errors.TypeError(
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string. Received type number
    at new Buffer (buffer.js:164:13)
    at Object.exports.uint256BufferFromHash (/root/node-open-mining-portal/node_modules/stratum-pool/lib/util.js:54:19)
    at Object.exports.CreateGeneration (/root/node-open-mining-portal/node_modules/stratum-pool/lib/transactions.js:222:14)
    at new BlockTemplate (/root/node-open-mining-portal/node_modules/stratum-pool/lib/blockTemplate.js:68:47)
    at JobManager.processTemplate (/root/node-open-mining-portal/node_modules/stratum-pool/lib/jobManager.js:154:32)
    at /root/node-open-mining-portal/node_modules/stratum-pool/lib/pool.js:576:62
    at itemFinished (/root/node-open-mining-portal/node_modules/stratum-pool/lib/daemon.js:156:36)
    at /root/node-open-mining-portal/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/root/node-open-mining-portal/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/node-open-mining-portal/node_modules/stratum-pool/lib/daemon.js:95:17)
```

Nodejs version 9.8

Will appreciate any help.

Thanks,
Ivan

**Comment by bitbandi** [comment]
Hi @Punkoivan . the error is here: https://github.com/zone117x/node-stratum-pool/blob/master/lib/transactions.js#L193

Try change that line to this (0 -> ""):

    var txInPrevOutHash = "";

**Comment by Punkoivan** [comment]
@bitbandi  you're the man! Looks like issue is solved! Great work.

I can confirm that code is working (sha256 for sure, checking with x11), please merge and test if you have some doubt.

**Comment by btcdio** [comment]
https://github.com/eveybcd/x13bcd_hash
please add this hash in the hashing  ,  thanks very much ~

this hashis    bitcoindiamond hash.

**Comment by HashUnlimited** [comment]
from our side tested and confirmed working as well. ack to merge.

**Comment by zone117x** [comment]
@HashUnlimited So does this pull provide support for new nodejs versions as well as compatibility with the current old version?

@bitbandi Great work, thanks you!!

@HashUnlimited Thanks a lot for helping out with reviews

**Comment by HashUnlimited** [comment]
on our tests yes, limitation for the whole bundle is to merge @bitbandi PR #141 [https://github.com/zone117x/node-stratum-pool/pull/141](url) as well because that's addressing an ancient bug not tolerated by newer nodes versions anymore

**Comment by zone117x** [comment]
@bitbandi Could you resolve the merge conflict in multihashing.cc and I'll merge?
Thanks again

**Pull request merged**
